"""add_fd_closure_fields

Revision ID: 9d84c9cd8634
Revises: c8d3e5f7a012
Create Date: 2026-02-13 12:17:04.517009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d84c9cd8634'
down_revision: Union[str, Sequence[str], None] = 'c8d3e5f7a012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('closure_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('closure_amount', sa.Float(), nullable=True))
        batch_op.create_index('idx_fd_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_deposits', schema=None) as batch_op:
        batch_op.drop_index('idx_fd_status')
        batch_op.drop_column('closure_amount')
        batch_op.drop_column('closure_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
