"""add_funded_externally_to_fixed_deposits

Revision ID: b799c23938f2
Revises: 9d84c9cd8634
Create Date: 2026-02-17 21:53:26.592156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b799c23938f2'
down_revision: Union[str, Sequence[str], None] = '9d84c9cd8634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funded_externally', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_deposits', schema=None) as batch_op:
        batch_op.drop_column('funded_externally')

    # ### end Alembic commands ###
